export const SANDBOX_TRANSPORT_METHODS = Object.freeze([
  'readFile',
  'lsFiles',
  'findFiles',
  'grepFiles',
  'writeFile',
  'editFile',
  'bash',
  'python',
  'processStart',
  'processStatus',
  'processRead',
  'processKill',
  'submitArtifact',
]);
