/**
 * Governed per-user Skill lifecycle tools.
 *
 * New Skills can only come from a current-turn ZIP attachment or from
 * structured content generated by the Agent. All mutations pass through the
 * enterprise policy/approval pipeline before execution.
 */
import { Type } from 'typebox';
import { toolOk, toolResultJson } from '../sandbox-bridge/result.js';
import { SKILL_LIFECYCLE_TOOL_NAMES } from './constants.js';

export { SKILL_LIFECYCLE_TOOL_NAMES };

function skillToolResult(value, opts = {}) {
  return toolOk(toolResultJson(value), value, {
    maxDetailString: opts.maxDetailString ?? 2_048,
  });
}

function compactSkillRecords(skills) {
  if (!Array.isArray(skills)) return [];
  return skills.map((raw) => {
    if (!raw || typeof raw !== 'object') {
      return { name: String(raw ?? ''), tier: 'unknown', editable: false };
    }
    const tier = raw.tier === 'user'
      ? 'user'
      : raw.tier === 'system'
        ? 'system'
        : 'unknown';
    const description = typeof raw.description === 'string'
      ? raw.description.slice(0, 400)
      : undefined;
    return {
      name: String(raw.name ?? ''),
      tier,
      editable: tier === 'user' || raw.editable === true,
      path: raw.path != null ? String(raw.path) : undefined,
      root: raw.root != null ? String(raw.root) : undefined,
      ...(description !== undefined ? { description } : {}),
    };
  });
}

function buildSkillListPayload(input) {
  const skills = compactSkillRecords(input.skills);
  const system = skills.filter((skill) => skill.tier === 'system');
  const user = skills.filter((skill) => skill.tier === 'user');
  return {
    skills,
    counts: { total: skills.length, system: system.length, user: user.length },
    system_skills: system,
    user_skills: user,
    user_skill_root: input.userSkillRoot ?? null,
    skill_roots: Array.isArray(input.skillRoots) ? input.skillRoots : [],
    tiers: {
      system: 'Bundled, read-only Skills. They cannot be replaced, edited or removed.',
      user: 'Per-user Skills. Lifecycle mutations affect only the calling user.',
    },
  };
}

function toolError(error, action) {
  const message = error instanceof Error ? error.message : String(error);
  return Object.assign(new Error(`skill_${action} failed: ${message}`), {
    code: 'SKILL_LIFECYCLE_FAILED',
  });
}

function normalizeCurrentTurnAttachments(value) {
  if (!Array.isArray(value)) return [];
  return value.flatMap((raw) => {
    if (!raw || typeof raw !== 'object') return [];
    const attachmentId = String(raw.attachmentId ?? raw.attachment_id ?? '').trim();
    const filename = String(raw.filename ?? raw.name ?? '').trim();
    if (!attachmentId || !filename) return [];
    return [{
      attachmentId,
      filename,
      mimeType: String(raw.mimeType ?? raw.mime_type ?? '').trim().toLowerCase(),
      size: Number(raw.size) || 0,
    }];
  });
}

async function mutateAndReload(manager, mutation) {
  const result = await mutation();
  let reload;
  try {
    reload = await manager.reload();
  } catch (error) {
    reload = {
      reloaded: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
  return { ...result, reload };
}

/**
 * @param {{
 *   runContext: object,
 *   deps?: {
 *     skillManager?: object | null,
 *     currentTurnAttachments?: object[],
 *   },
 * }} options
 */
export function createSkillLifecycleExtension(options) {
  const manager = options?.deps?.skillManager ?? null;
  if (
    !manager ||
    typeof manager.install !== 'function' ||
    typeof manager.create !== 'function'
  ) {
    throw new Error(
      'SKILL_MANAGER_REQUIRED: skill-lifecycle requires install/create support',
    );
  }
  if (!manager.userSkillRoot) {
    throw new Error(
      'SKILL_USER_ROOT_REQUIRED: skill-lifecycle requires a per-user Skill directory',
    );
  }
  const currentTurnAttachments = normalizeCurrentTurnAttachments(
    options?.deps?.currentTurnAttachments,
  );

  function skillLifecycleExtension(pi) {
    pi.registerTool({
      name: 'skill_list',
      label: 'List Skills',
      description:
        'List bundled read-only Skills and the current user\'s installed Skills.',
      promptSnippet: 'Inspect bundled and user-installed Skills',
      parameters: Type.Object({}),
      async execute() {
        try {
          return skillToolResult(
            buildSkillListPayload({
              skills: manager.describeInstalled(),
              userSkillRoot: manager.userSkillRoot,
              skillRoots: manager.skillRoots,
            }),
          );
        } catch (error) {
          throw toolError(error, 'list');
        }
      },
    });

    pi.registerTool({
      name: 'skill_install',
      label: 'Install uploaded Skill',
      description:
        'Install exactly one Skill from a ZIP file attached by the user in the current turn. ' +
        'Use the attachment_id and filename from the current-turn attachment block. ' +
        'URLs and filesystem paths are not accepted. This operation requires user approval.',
      promptSnippet: 'Install a current-turn Skill ZIP attachment after approval',
      promptGuidelines: [
        'Only call this for a .zip attachment in the current user turn.',
        'Copy attachment_id and filename exactly from the attachment block.',
        'Install only through the attachment fields exposed for this turn.',
      ],
      parameters: Type.Object({
        attachment_id: Type.String({ minLength: 1, maxLength: 128 }),
        filename: Type.String({ minLength: 1, maxLength: 255 }),
      }),
      async execute(_toolCallId, input) {
        try {
          const attachment = currentTurnAttachments.find(
            (item) => item.attachmentId === String(input.attachment_id).trim(),
          );
          if (!attachment) {
            throw new Error(
              'attachment_id is not bound to a file in the current user turn; attach the ZIP again',
            );
          }
          if (attachment.filename !== input.filename) {
            throw new Error('filename does not match the current-turn attachment');
          }
          if (!attachment.filename.toLowerCase().endsWith('.zip')) {
            throw new Error('Skill installation accepts .zip attachments only');
          }
          return skillToolResult(
            await mutateAndReload(manager, () =>
              manager.install({
                attachmentId: attachment.attachmentId,
                archiveName: attachment.filename,
                declaredSize: attachment.size,
              }),
            ),
          );
        } catch (error) {
          throw toolError(error, 'install');
        }
      },
    });

    pi.registerTool({
      name: 'skill_create',
      label: 'Create generated Skill',
      description:
        'Create or replace one user Skill from requirements discussed with the user. ' +
        'Provide the complete SKILL.md body as instructions and optional text files. ' +
        'This is an installation operation and requires user approval.',
      promptSnippet: 'Generate and install a user Skill after approval',
      promptGuidelines: [
        'Confirm material requirements with the user before creating the package.',
        'Use a lowercase slug for name and make instructions self-contained.',
        'Do not include SKILL.md in files; it is generated from the structured fields.',
      ],
      parameters: Type.Object({
        name: Type.String({ minLength: 1, maxLength: 64 }),
        description: Type.String({ minLength: 1, maxLength: 500 }),
        instructions: Type.String({ minLength: 1, maxLength: 400_000 }),
        files: Type.Optional(
          Type.Array(
            Type.Object({
              path: Type.String({ minLength: 1, maxLength: 1024 }),
              content: Type.String({ maxLength: 400_000 }),
            }),
            { maxItems: 32 },
          ),
        ),
      }),
      async execute(_toolCallId, input) {
        try {
          return skillToolResult(
            await mutateAndReload(manager, () => manager.create(input)),
          );
        } catch (error) {
          throw toolError(error, 'create');
        }
      },
    });

    pi.registerTool({
      name: 'skill_edit',
      label: 'Edit installed Skill',
      description:
        'Replace one file inside an existing user Skill. This cannot create a new Skill. ' +
        'Bundled Skills are read-only. This operation requires user approval.',
      promptSnippet: 'Edit one file in an installed user Skill after approval',
      parameters: Type.Object({
        path: Type.String({ minLength: 1, maxLength: 1024 }),
        content: Type.String(),
      }),
      async execute(_toolCallId, input) {
        try {
          return skillToolResult(
            await mutateAndReload(manager, () => manager.edit(input)),
          );
        } catch (error) {
          throw toolError(error, 'edit');
        }
      },
    });

    pi.registerTool({
      name: 'skill_uninstall',
      label: 'Uninstall Skill',
      description:
        'Remove one user-installed Skill. Bundled Skills cannot be removed. ' +
        'This operation requires user approval.',
      promptSnippet: 'Remove a user-installed Skill after approval',
      parameters: Type.Object({
        name: Type.String({ minLength: 1, maxLength: 64 }),
      }),
      async execute(_toolCallId, input) {
        try {
          return skillToolResult(
            await mutateAndReload(manager, () => manager.uninstall(input)),
          );
        } catch (error) {
          throw toolError(error, 'uninstall');
        }
      },
    });
  }

  skillLifecycleExtension.extensionName = 'skill-lifecycle';
  skillLifecycleExtension.extensionMetadata = Object.freeze({
    name: 'skill-lifecycle',
    role: 'skill-lifecycle',
    failClosed: true,
    toolsRegistered: true,
    mutationsRequireApproval: true,
    tools: SKILL_LIFECYCLE_TOOL_NAMES,
  });
  return skillLifecycleExtension;
}
