/**
 * Short-lived Agent -> Sandbox internal tokens.
 *
 * This module intentionally implements only HS256 with a strict, closed
 * schema. It does not accept general JWT algorithms, permissive numeric
 * coercion, unknown claims, padded base64url, or an unknown-kid fallback.
 */

import {
  createHmac,
  randomBytes as cryptoRandomBytes,
  timingSafeEqual,
} from 'node:crypto';
import { TextDecoder } from 'node:util';

/** 过渡期宽松类型：注入的依赖多数还是 JS 类，形状由各自的模块负责。 */
type Loose = any;

export const INTERNAL_TOKEN_ALGORITHM = 'HS256';
export const INTERNAL_TOKEN_TYPE = 'sandbox-internal+jwt';
export const INTERNAL_TOKEN_VERSION = 1;
export const INTERNAL_TOKEN_ISSUER = 'agent-service';
export const INTERNAL_TOKEN_AUDIENCE = 'sandbox-service';
export const INTERNAL_TOKEN_SUBJECT = 'agent-worker';
export const INTERNAL_TOKEN_DEFAULT_TTL_SECONDS = 60;
export const INTERNAL_TOKEN_MAX_TTL_SECONDS = 120;

export const INTERNAL_TOKEN_HEADER_KEYS = Object.freeze([
  'alg',
  'kid',
  'typ',
]);

export const INTERNAL_TOKEN_CLAIM_KEYS = Object.freeze([
  'token_version',
  'iss',
  'aud',
  'sub',
  'org_id',
  'user_id',
  'conversation_id',
  'agent_session_id',
  'sandbox_session_id',
  'run_id',
  'tool_execution_id',
  'tool_call_id',
  'tool_name',
  'scope',
  'request_hash',
  'request_hash_version',
  'execution_fence_token',
  'trace_id',
  'htm',
  'htu',
  'body_sha256',
  'iat',
  'nbf',
  'exp',
  'jti',
]);

/**
 * Claims supplied by the caller when issuing a token. Service identity,
 * versions, time claims, and jti are generated by this module.
 */
export const INTERNAL_TOKEN_ISSUE_CLAIM_KEYS = Object.freeze([
  'org_id',
  'user_id',
  'conversation_id',
  'agent_session_id',
  'sandbox_session_id',
  'run_id',
  'tool_execution_id',
  'tool_call_id',
  'tool_name',
  'scope',
  'request_hash',
  'execution_fence_token',
  'trace_id',
  'htm',
  'htu',
  'body_sha256',
]);

const MAX_KID_LENGTH = 128;
const MAX_IDENTIFIER_LENGTH = 255;
const MAX_SCOPE_LENGTH = 128;
const MAX_HTU_LENGTH = 2048;
const MAX_KEYRING_KEYS = 32;
const MAX_KEY_BYTES = 4096;
const MAX_KEYRING_JSON_BYTES = 64 * 1024;
const SHA256_HEX_RE = /^[0-9a-f]{64}$/;
const BASE64URL_RE = /^[A-Za-z0-9_-]+$/;
const KID_RE = /^[A-Za-z0-9._-]+$/;
const PRINTABLE_ASCII_RE = /^[\x21-\x7e]+$/;
const UTF8_FATAL_DECODER = new TextDecoder('utf-8', { fatal: true });

export class InternalHmacError extends Error {
  // TS 要求类字段显式声明（JS 里它们只在构造器里赋值）。
  code: Loose;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'InternalHmacError';
    this.code = code;
  }
}

/**
 * 永远抛出。返回类型必须写 `never`——否则 TS 认为它可能正常返回，
 * 所有「校验失败就 fail(...)」的守卫都不会收窄类型，后面每一次读字段
 * 都会报 unknown。
 */
function fail(code: string, message: string): never {
  throw new InternalHmacError(code, message);
}

/**
 */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

/**
 * Reject symbols, non-enumerable properties and accessors as well as ordinary
 * missing/extra keys. This keeps the object accepted here identical to the
 * object that is serialized.
 *
 * @param value
 * @param expected
 * @param label
 * @returns {Record<string, unknown>}
 */
function assertExactObjectKeys(value: unknown, expected: readonly string[], label: string) {
  if (!isPlainObject(value)) {
    fail('INTERNAL_TOKEN_SCHEMA_INVALID', `${label} must be a plain object`);
  }

  const object = (value as Record<string, unknown>);
  const ownKeys = Reflect.ownKeys(object);
  if (
    ownKeys.length !== expected.length ||
    ownKeys.some((key) => typeof key !== 'string' || !expected.includes(key))
  ) {
    fail(
      'INTERNAL_TOKEN_SCHEMA_INVALID',
      `${label} must contain exactly: ${expected.join(',')}`,
    );
  }

  for (const key of expected) {
    const descriptor = Object.getOwnPropertyDescriptor(object, key);
    if (
      !descriptor ||
      !descriptor.enumerable ||
      !Object.hasOwn(descriptor, 'value')
    ) {
      fail(
        'INTERNAL_TOKEN_SCHEMA_INVALID',
        `${label}.${key} must be an enumerable data property`,
      );
    }
  }
  return object;
}

/**
 * @param {unknown} value
 * @param {string} field
 * @param {number} maxLength
 * @returns {string}
 */
function assertAsciiIdentifier(
  value,
  field,
  maxLength = MAX_IDENTIFIER_LENGTH,
) {
  if (
    typeof value !== 'string' ||
    value.length === 0 ||
    value.length > maxLength ||
    !PRINTABLE_ASCII_RE.test(value)
  ) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      `${field} must be 1..${maxLength} printable ASCII characters`,
    );
  }
  return value;
}

/**
 * @param value
 * @param field
 * @returns {number}
 */
function assertPositiveSafeInteger(value: unknown, field: string) {
  if (
    typeof value !== 'number' ||
    !Number.isSafeInteger(value) ||
    value <= 0
  ) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      `${field} must be a positive safe integer number`,
    );
  }
  return value;
}

/**
 * Strict unpadded canonical base64url decoder.
 *
 * @param value
 * @param field
 * @returns {Buffer}
 */
function decodeCanonicalBase64url(value: unknown, field: string) {
  if (
    typeof value !== 'string' ||
    value.length === 0 ||
    !BASE64URL_RE.test(value) ||
    value.length % 4 === 1
  ) {
    fail(
      'INTERNAL_TOKEN_BASE64URL_INVALID',
      `${field} must be canonical unpadded base64url`,
    );
  }
  const decoded = Buffer.from(value, 'base64url');
  if (decoded.toString('base64url') !== value) {
    fail(
      'INTERNAL_TOKEN_BASE64URL_INVALID',
      `${field} must be canonical unpadded base64url`,
    );
  }
  return decoded;
}

/**
 * Parse a flat JSON object whose keys and values are strings, preserving the
 * ability to reject duplicate keys (JSON.parse alone would silently replace
 * them).
 *
 * @param source
 * @returns {Record<string, string>}
 */
function parseJsonKeyring(source: string) {
  if (Buffer.byteLength(source, 'utf8') > MAX_KEYRING_JSON_BYTES) {
    fail('INTERNAL_TOKEN_KEYRING_INVALID', 'keyring JSON is too large');
  }

  let offset = 0;
  const result = Object.create(null);

  const skipWhitespace = () => {
    while (
      offset < source.length &&
      (source[offset] === ' ' ||
        source[offset] === '\t' ||
        source[offset] === '\r' ||
        source[offset] === '\n')
    ) {
      offset += 1;
    }
  };

  const parseString = () => {
    if (source[offset] !== '"') {
      fail(
        'INTERNAL_TOKEN_KEYRING_INVALID',
        'keyring JSON keys and values must be strings',
      );
    }
    const start = offset;
    offset += 1;
    let escaped = false;
    while (offset < source.length) {
      const code = source.charCodeAt(offset);
      const character = source[offset];
      if (!escaped && character === '"') {
        offset += 1;
        try {
          return JSON.parse(source.slice(start, offset));
        } catch {
          fail('INTERNAL_TOKEN_KEYRING_INVALID', 'invalid keyring JSON string');
        }
      }
      if (!escaped && code < 0x20) {
        fail('INTERNAL_TOKEN_KEYRING_INVALID', 'invalid keyring JSON string');
      }
      if (!escaped && character === '\\') {
        escaped = true;
      } else {
        escaped = false;
      }
      offset += 1;
    }
    fail('INTERNAL_TOKEN_KEYRING_INVALID', 'unterminated keyring JSON string');
  };

  skipWhitespace();
  if (source[offset] !== '{') {
    fail('INTERNAL_TOKEN_KEYRING_INVALID', 'keyring JSON must be an object');
  }
  offset += 1;
  skipWhitespace();
  if (source[offset] === '}') {
    offset += 1;
  } else {
    while (offset < source.length) {
      const key = parseString();
      if (Object.hasOwn(result, key)) {
        fail(
          'INTERNAL_TOKEN_KEYRING_INVALID',
          `duplicate keyring kid: ${key}`,
        );
      }
      skipWhitespace();
      if (source[offset] !== ':') {
        fail('INTERNAL_TOKEN_KEYRING_INVALID', 'invalid keyring JSON object');
      }
      offset += 1;
      skipWhitespace();
      const value = parseString();
      result[key] = value;
      skipWhitespace();
      if (source[offset] === '}') {
        offset += 1;
        break;
      }
      if (source[offset] !== ',') {
        fail('INTERNAL_TOKEN_KEYRING_INVALID', 'invalid keyring JSON object');
      }
      offset += 1;
      skipWhitespace();
    }
  }
  skipWhitespace();
  if (offset !== source.length) {
    fail(
      'INTERNAL_TOKEN_KEYRING_INVALID',
      'unexpected data after keyring JSON object',
    );
  }
  return result;
}

/**
 * @param input
 * @returns {Map<string, Buffer>}
 */
function decodeKeyring(input: unknown) {
  let object;
  if (typeof input === 'string') {
    object = parseJsonKeyring(input);
  } else {
    if (!isPlainObject(input)) {
      fail(
        'INTERNAL_TOKEN_KEYRING_INVALID',
        'keyring must be an object or JSON object string',
      );
    }
    object = (input as Record<string, unknown>);
    for (const key of Reflect.ownKeys(object)) {
      if (typeof key !== 'string') {
        fail(
          'INTERNAL_TOKEN_KEYRING_INVALID',
          'keyring cannot contain symbol keys',
        );
      }
      const descriptor = Object.getOwnPropertyDescriptor(object, key);
      if (
        !descriptor ||
        !descriptor.enumerable ||
        !Object.hasOwn(descriptor, 'value') ||
        typeof descriptor.value !== 'string'
      ) {
        fail(
          'INTERNAL_TOKEN_KEYRING_INVALID',
          'keyring values must be enumerable string data properties',
        );
      }
    }
  }

  const entries = Object.entries(object);
  if (entries.length === 0 || entries.length > MAX_KEYRING_KEYS) {
    fail(
      'INTERNAL_TOKEN_KEYRING_INVALID',
      `keyring must contain 1..${MAX_KEYRING_KEYS} keys`,
    );
  }

  const decoded = new Map();
  for (const [kid, encoded] of entries) {
    if (
      kid.length === 0 ||
      kid.length > MAX_KID_LENGTH ||
      !KID_RE.test(kid)
    ) {
      fail(
        'INTERNAL_TOKEN_KEYRING_INVALID',
        `kid must match ${KID_RE} and be at most ${MAX_KID_LENGTH} characters`,
      );
    }
    const key = decodeCanonicalBase64url(encoded, `keyring.${kid}`);
    if (key.length < 32 || key.length > MAX_KEY_BYTES) {
      fail(
        'INTERNAL_TOKEN_KEYRING_INVALID',
        `keyring.${kid} must decode to 32..${MAX_KEY_BYTES} bytes`,
      );
    }
    decoded.set(kid, key);
  }
  return decoded;
}

/**
 * Validate a keyring and active signing kid without exposing a fallback key.
 *
 * @param keyring
 * @param activeKid
 * @returns {{activeKid: string, kids: readonly string[]}}
 */
export function validateInternalHmacKeyring(keyring: unknown, activeKid: unknown) {
  const decoded = decodeKeyring(keyring);
  const kid = assertAsciiIdentifier(activeKid, 'activeKid', MAX_KID_LENGTH);
  if (!KID_RE.test(kid) || !decoded.has(kid)) {
    fail(
      'INTERNAL_TOKEN_ACTIVE_KID_UNKNOWN',
      'activeKid must identify an existing keyring entry',
    );
  }
  return Object.freeze({
    activeKid: kid,
    kids: Object.freeze([...decoded.keys()]),
  });
}

/**
 * @param value
 * @param field
 * @returns {string}
 */
function assertSha256(value: unknown, field: string) {
  if (typeof value !== 'string' || !SHA256_HEX_RE.test(value)) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      `${field} must be 64 lowercase hexadecimal characters`,
    );
  }
  return value;
}

/**
 * @param value
 * @returns {string}
 */
function assertHtu(value: unknown) {
  if (
    typeof value !== 'string' ||
    value.length === 0 ||
    value.length > MAX_HTU_LENGTH ||
    value[0] !== '/' ||
    !PRINTABLE_ASCII_RE.test(value) ||
    value.includes('?') ||
    value.includes('#')
  ) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      `htu must be an ASCII absolute path without query/fragment and at most ${MAX_HTU_LENGTH} characters`,
    );
  }
  return value;
}

/**
 * @param value
 * @returns {readonly [string]}
 */
function assertScope(value: unknown) {
  if (
    !Array.isArray(value) ||
    value.length !== 1 ||
    Reflect.ownKeys(value).some(
      (key) => key !== '0' && key !== 'length',
    )
  ) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      'scope must contain exactly one element',
    );
  }
  return Object.freeze([
    assertAsciiIdentifier(value[0], 'scope[0]', MAX_SCOPE_LENGTH),
  ]);
}

/**
 * Validate and copy the exact final claim set in deterministic serialization
 * order.
 *
 * @param input
 * @returns {Readonly<Record<string, unknown>>}
 */
export function validateInternalTokenClaims(input: unknown) {
  const claims = assertExactObjectKeys(
    input,
    INTERNAL_TOKEN_CLAIM_KEYS,
    'claims',
  );

  if (claims.token_version !== INTERNAL_TOKEN_VERSION) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      `token_version must equal ${INTERNAL_TOKEN_VERSION}`,
    );
  }
  if (claims.request_hash_version !== 1) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      'request_hash_version must equal 1',
    );
  }
  if (claims.iss !== INTERNAL_TOKEN_ISSUER) {
    fail('INTERNAL_TOKEN_CLAIM_INVALID', 'iss is invalid');
  }
  if (claims.aud !== INTERNAL_TOKEN_AUDIENCE) {
    fail('INTERNAL_TOKEN_CLAIM_INVALID', 'aud is invalid');
  }
  if (claims.sub !== INTERNAL_TOKEN_SUBJECT) {
    fail('INTERNAL_TOKEN_CLAIM_INVALID', 'sub is invalid');
  }

  const toolName = assertAsciiIdentifier(claims.tool_name, 'tool_name');
  const scope = assertScope(claims.scope);
  const isPreRunSessionEnsure =
    toolName === 'session.ensure' &&
    scope[0] === 'sandbox.sessions.ensure' &&
    claims.htu === '/internal/v1/sessions/ensure' &&
    claims.run_id === null &&
    claims.execution_fence_token === null;

  const normalized = {
    token_version: INTERNAL_TOKEN_VERSION,
    iss: INTERNAL_TOKEN_ISSUER,
    aud: INTERNAL_TOKEN_AUDIENCE,
    sub: INTERNAL_TOKEN_SUBJECT,
    org_id: assertAsciiIdentifier(claims.org_id, 'org_id'),
    user_id: assertAsciiIdentifier(claims.user_id, 'user_id'),
    conversation_id: assertAsciiIdentifier(
      claims.conversation_id,
      'conversation_id',
    ),
    agent_session_id: assertAsciiIdentifier(
      claims.agent_session_id,
      'agent_session_id',
    ),
    sandbox_session_id: assertAsciiIdentifier(
      claims.sandbox_session_id,
      'sandbox_session_id',
    ),
    run_id: isPreRunSessionEnsure
      ? null
      : assertAsciiIdentifier(claims.run_id, 'run_id'),
    tool_execution_id: assertAsciiIdentifier(
      claims.tool_execution_id,
      'tool_execution_id',
    ),
    tool_call_id: assertAsciiIdentifier(claims.tool_call_id, 'tool_call_id'),
    tool_name: toolName,
    scope,
    request_hash: assertSha256(claims.request_hash, 'request_hash'),
    request_hash_version: 1,
    execution_fence_token: isPreRunSessionEnsure
      ? null
      : assertPositiveSafeInteger(
          claims.execution_fence_token,
          'execution_fence_token',
        ),
    trace_id: assertAsciiIdentifier(claims.trace_id, 'trace_id'),
    htm: claims.htm,
    htu: assertHtu(claims.htu),
    body_sha256: assertSha256(claims.body_sha256, 'body_sha256'),
    iat: assertPositiveSafeInteger(claims.iat, 'iat'),
    nbf: assertPositiveSafeInteger(claims.nbf, 'nbf'),
    exp: assertPositiveSafeInteger(claims.exp, 'exp'),
    jti: claims.jti,
  };

  if (normalized.htm !== 'POST') {
    fail('INTERNAL_TOKEN_CLAIM_INVALID', 'htm must equal POST');
  }
  if (normalized.nbf !== normalized.iat) {
    fail('INTERNAL_TOKEN_CLAIM_INVALID', 'nbf must equal iat');
  }
  const ttl = normalized.exp - normalized.iat;
  if (ttl <= 0 || ttl > INTERNAL_TOKEN_MAX_TTL_SECONDS) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      `exp-iat must be in 1..${INTERNAL_TOKEN_MAX_TTL_SECONDS}`,
    );
  }

  const jtiBytes = decodeCanonicalBase64url(normalized.jti, 'jti');
  if (jtiBytes.length !== 16) {
    fail('INTERNAL_TOKEN_CLAIM_INVALID', 'jti must encode exactly 128 bits');
  }
  normalized.jti = (claims.jti as string);

  return Object.freeze(normalized);
}

/**
 * @param input
 * @returns {Readonly<Record<string, unknown>>}
 */
function validateIssueClaims(input: unknown) {
  const claims = assertExactObjectKeys(
    input,
    INTERNAL_TOKEN_ISSUE_CLAIM_KEYS,
    'issue claims',
  );
  const toolName = assertAsciiIdentifier(claims.tool_name, 'tool_name');
  const scope = assertScope(claims.scope);
  const isPreRunSessionEnsure =
    toolName === 'session.ensure' &&
    scope[0] === 'sandbox.sessions.ensure' &&
    claims.htu === '/internal/v1/sessions/ensure' &&
    claims.run_id === null &&
    claims.execution_fence_token === null;
  return Object.freeze({
    org_id: assertAsciiIdentifier(claims.org_id, 'org_id'),
    user_id: assertAsciiIdentifier(claims.user_id, 'user_id'),
    conversation_id: assertAsciiIdentifier(
      claims.conversation_id,
      'conversation_id',
    ),
    agent_session_id: assertAsciiIdentifier(
      claims.agent_session_id,
      'agent_session_id',
    ),
    sandbox_session_id: assertAsciiIdentifier(
      claims.sandbox_session_id,
      'sandbox_session_id',
    ),
    run_id: isPreRunSessionEnsure
      ? null
      : assertAsciiIdentifier(claims.run_id, 'run_id'),
    tool_execution_id: assertAsciiIdentifier(
      claims.tool_execution_id,
      'tool_execution_id',
    ),
    tool_call_id: assertAsciiIdentifier(claims.tool_call_id, 'tool_call_id'),
    tool_name: toolName,
    scope,
    request_hash: assertSha256(claims.request_hash, 'request_hash'),
    execution_fence_token: isPreRunSessionEnsure
      ? null
      : assertPositiveSafeInteger(
          claims.execution_fence_token,
          'execution_fence_token',
        ),
    trace_id: assertAsciiIdentifier(claims.trace_id, 'trace_id'),
    htm: claims.htm === 'POST' ? 'POST' : fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      'htm must equal POST',
    ),
    htu: assertHtu(claims.htu),
    body_sha256: assertSha256(claims.body_sha256, 'body_sha256'),
  });
}

/**
 * @param now
 * @returns {number}
 */
function assertClockSeconds(now: unknown) {
  return assertPositiveSafeInteger(now, 'clock result');
}

/**
 * @param bytes
 * @returns {string}
 */
function encodeBase64url(bytes: Buffer) {
  return bytes.toString('base64url');
}

/**
 * Deterministically sign an already-complete, strictly validated claim set.
 *
 * @param {{
 *   keyring: object|string,
 *   activeKid: string,
 *   claims: object,
 * }} options
 * @returns {string}
 */
export function signInternalToken(options: { keyring: Record<string, any>|string, activeKid: string, claims: Record<string, any>, }) {
  const decoded = decodeKeyring(options?.keyring);
  const activeKid = assertAsciiIdentifier(
    options?.activeKid,
    'activeKid',
    MAX_KID_LENGTH,
  );
  if (!KID_RE.test(activeKid) || !decoded.has(activeKid)) {
    fail(
      'INTERNAL_TOKEN_ACTIVE_KID_UNKNOWN',
      'activeKid must identify an existing keyring entry',
    );
  }
  const claims = validateInternalTokenClaims(options?.claims);
  const header = {
    alg: INTERNAL_TOKEN_ALGORITHM,
    kid: activeKid,
    typ: INTERNAL_TOKEN_TYPE,
  };
  const signingInput =
    `${encodeBase64url(Buffer.from(JSON.stringify(header), 'utf8'))}.` +
    encodeBase64url(Buffer.from(JSON.stringify(claims), 'utf8'));
  const signature = createHmac('sha256', decoded.get(activeKid))
    .update(signingInput, 'ascii')
    .digest();
  return `${signingInput}.${encodeBase64url(signature)}`;
}

/**
 * Create a short-lived token, injecting a Unix-seconds clock and a 16-byte
 * random source for deterministic tests.
 *
 * @param {{
 *   keyring: object|string,
 *   activeKid: string,
 *   claims: object,
 *   ttlSeconds?: number,
 *   clock?: () => number,
 *   randomBytes?: (size: number) => Uint8Array,
 * }} options
 * @returns {string}
 */
export function issueInternalToken(options: { keyring: Record<string, any>|string, activeKid: string, claims: Record<string, any>, ttlSeconds?: number, clock?: () => number, randomBytes?: (size: number) => Uint8Array, }) {
  const ttl = options?.ttlSeconds ?? INTERNAL_TOKEN_DEFAULT_TTL_SECONDS;
  if (
    typeof ttl !== 'number' ||
    !Number.isSafeInteger(ttl) ||
    ttl <= 0 ||
    ttl > INTERNAL_TOKEN_MAX_TTL_SECONDS
  ) {
    fail(
      'INTERNAL_TOKEN_TTL_INVALID',
      `ttlSeconds must be a safe integer in 1..${INTERNAL_TOKEN_MAX_TTL_SECONDS}`,
    );
  }
  const now = assertClockSeconds(
    (options?.clock ?? (() => Math.floor(Date.now() / 1000)))(),
  );
  if (!Number.isSafeInteger(now + ttl)) {
    fail('INTERNAL_TOKEN_TTL_INVALID', 'token expiry is not a safe integer');
  }
  const randomSource = options?.randomBytes ?? cryptoRandomBytes;
  if (typeof randomSource !== 'function') {
    fail(
      'INTERNAL_TOKEN_RANDOM_INVALID',
      'randomBytes must be a function',
    );
  }
  const random = randomSource(16);
  if (!(random instanceof Uint8Array) || random.byteLength !== 16) {
    fail(
      'INTERNAL_TOKEN_RANDOM_INVALID',
      'randomBytes must return exactly 16 bytes',
    );
  }
  const input = validateIssueClaims(options?.claims);
  const claims = {
    token_version: INTERNAL_TOKEN_VERSION,
    iss: INTERNAL_TOKEN_ISSUER,
    aud: INTERNAL_TOKEN_AUDIENCE,
    sub: INTERNAL_TOKEN_SUBJECT,
    ...input,
    request_hash_version: 1,
    iat: now,
    nbf: now,
    exp: now + ttl,
    jti: encodeBase64url(Buffer.from(random)),
  };
  // Rebuild in the one authoritative order before signing.
  const orderedClaims = Object.fromEntries(
    INTERNAL_TOKEN_CLAIM_KEYS.map((key) => [key, claims[key]]),
  );
  return signInternalToken({
    keyring: options?.keyring,
    activeKid: options?.activeKid,
    claims: orderedClaims,
  });
}

/**
 * @param segment
 * @param field
 * @returns {{text: string, value: unknown}}
 */
function decodeJwtJsonSegment(segment: string, field: string) {
  const bytes = decodeCanonicalBase64url(segment, field);
  let text;
  try {
    text = UTF8_FATAL_DECODER.decode(bytes);
  } catch {
    fail('INTERNAL_TOKEN_MALFORMED', `${field} is not valid UTF-8`);
  }
  try {
    return { text, value: JSON.parse(text) };
  } catch {
    fail('INTERNAL_TOKEN_MALFORMED', `${field} is not valid JSON`);
  }
}

/**
 * Verify signature, exact schemas, canonical compact serialization, fixed
 * issuer/audience/subject, and strict token time validity.
 *
 * @param token
 * @param {{
 *   keyring: object|string,
 *   clock?: () => number,
 * }} options
 * @returns {Readonly<Record<string, unknown>>}
 */
export function verifyInternalToken(token: string, options: { keyring: Record<string, any>|string, clock?: () => number, }) {
  if (typeof token !== 'string' || token.length > 16 * 1024) {
    fail('INTERNAL_TOKEN_MALFORMED', 'token must be a bounded string');
  }
  const segments = token.split('.');
  if (segments.length !== 3 || segments.some((part) => part.length === 0)) {
    fail(
      'INTERNAL_TOKEN_MALFORMED',
      'token must contain exactly three compact segments',
    );
  }

  const headerDecoded = decodeJwtJsonSegment(segments[0], 'header');
  const header = assertExactObjectKeys(
    headerDecoded.value,
    INTERNAL_TOKEN_HEADER_KEYS,
    'header',
  );
  if (
    header.alg !== INTERNAL_TOKEN_ALGORITHM ||
    header.typ !== INTERNAL_TOKEN_TYPE
  ) {
    fail('INTERNAL_TOKEN_HEADER_INVALID', 'unsupported token header');
  }
  const kid = assertAsciiIdentifier(header.kid, 'header.kid', MAX_KID_LENGTH);
  if (!KID_RE.test(kid)) {
    fail('INTERNAL_TOKEN_HEADER_INVALID', 'invalid header kid');
  }
  const canonicalHeader = JSON.stringify({
    alg: INTERNAL_TOKEN_ALGORITHM,
    kid,
    typ: INTERNAL_TOKEN_TYPE,
  });
  if (headerDecoded.text !== canonicalHeader) {
    fail(
      'INTERNAL_TOKEN_HEADER_INVALID',
      'header must use deterministic compact serialization',
    );
  }

  const decoded = decodeKeyring(options?.keyring);
  const key = decoded.get(kid);
  if (!key) {
    fail(
      'INTERNAL_TOKEN_UNKNOWN_KID',
      'token kid is not present in the keyring',
    );
  }

  const suppliedSignature = decodeCanonicalBase64url(
    segments[2],
    'signature',
  );
  const expectedSignature = createHmac('sha256', key)
    .update(`${segments[0]}.${segments[1]}`, 'ascii')
    .digest();
  if (
    suppliedSignature.length !== expectedSignature.length ||
    !timingSafeEqual(suppliedSignature, expectedSignature)
  ) {
    fail('INTERNAL_TOKEN_SIGNATURE_INVALID', 'invalid token signature');
  }

  const claimsDecoded = decodeJwtJsonSegment(segments[1], 'claims');
  const claims = validateInternalTokenClaims(claimsDecoded.value);
  if (claimsDecoded.text !== JSON.stringify(claims)) {
    fail(
      'INTERNAL_TOKEN_CLAIM_INVALID',
      'claims must use deterministic compact serialization',
    );
  }

  const now = assertClockSeconds(
    (options?.clock ?? (() => Math.floor(Date.now() / 1000)))(),
  );
  if (now < (claims.nbf as number)) {
    fail('INTERNAL_TOKEN_NOT_YET_VALID', 'token is not yet valid');
  }
  if (now >= (claims.exp as number)) {
    fail('INTERNAL_TOKEN_EXPIRED', 'token has expired');
  }
  return claims;
}

// ── baseUrl 归一化 ────────────────────────────────────────────────────────
//
// 2026-08-30 从 `internal-files-read-http.js` 搬来。那个文件连同其余 11 个
// `internal-*-http` 一起删除了（它们喂的 extension bundle 自 W6-A 起就是
// `return []`），但这两个存活的传输——会话开通与产物字节下载——都要它。
// 它属于"HMAC 传输的公共部分"，本来就该在这里。

/**
 * Literal loopback hostnames only — no DNS/CIDR invention.
 * @param hostname
 * @returns {boolean}
 */
function isLiteralLoopbackHostname(hostname: string) {
  const h = String(hostname || '')
    .toLowerCase()
    .replace(/^\[|\]$/g, '');
  return h === 'localhost' || h === '127.0.0.1' || h === '::1';
}

/**
 * @param baseUrl
 * @param [opts]
 * @returns {string}
 */
export function normalizeBaseUrl(baseUrl: string, opts: { allowInsecureHttp?: boolean } = {}) {
  if (typeof baseUrl !== 'string' || !baseUrl.trim()) {
    fail('SANDBOX_TRANSPORT_CONFIG', 'baseUrl is required');
  }
  const allowInsecureHttp = opts.allowInsecureHttp === true;
  const trimmed = baseUrl.trim().replace(/\/+$/, '');
  if (!/^https?:\/\/.+/i.test(trimmed)) {
    fail('SANDBOX_TRANSPORT_CONFIG', 'baseUrl must be an absolute http(s) URL');
  }
  let u;
  try {
    u = new URL(trimmed);
  } catch {
    fail('SANDBOX_TRANSPORT_CONFIG', 'baseUrl is not a valid URL');
  }
  if (u.username || u.password) {
    fail('SANDBOX_TRANSPORT_CONFIG', 'baseUrl must not embed credentials');
  }
  if (u.search || u.hash) {
    fail('SANDBOX_TRANSPORT_CONFIG', 'baseUrl must not include query/hash');
  }
  if (u.protocol === 'https:') {
    return trimmed;
  }
  if (u.protocol === 'http:') {
    // Default: only literal loopback over http. External/plain http requires
    // explicit allowInsecureHttp (dev/controlled). No CIDR/DNS policy here —
    // production config will tighten further.
    if (allowInsecureHttp || isLiteralLoopbackHostname(u.hostname)) {
      return trimmed;
    }
    fail(
      'SANDBOX_TRANSPORT_CONFIG',
      'http baseUrl rejected unless loopback or allowInsecureHttp=true',
    );
  }
  fail('SANDBOX_TRANSPORT_CONFIG', 'baseUrl scheme must be http or https');
}
