import type { ArtifactEntity } from '../../../entities';
import { getArtifactDownloadUrl, getDownloadUrl } from '../../../shared/api';
import { safeApiUrl } from '../../../shared/security/url';

function formatSize(n?: number | null): string {
  if (n == null || Number.isNaN(Number(n))) return '';
  const b = Number(n);
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / (1024 * 1024)).toFixed(1)} MB`;
}

/**
 * Artifact card — traces back to run (and tool via run context).
 */
export function ArtifactCard({
  artifact,
  sessionId,
  selected,
  onSelect,
}: {
  artifact: ArtifactEntity;
  sessionId?: string | null;
  selected?: boolean;
  onSelect?: (artifactId: string) => void;
}) {
  const size = formatSize(artifact.size);
  let url: string | null = null;
  const sid = sessionId || artifact.sessionId;
  if (sid && artifact.id) {
    url = getArtifactDownloadUrl(sid, artifact.id);
  } else if (sid && artifact.path) {
    url = getDownloadUrl(sid, artifact.path);
  }
  const safe = safeApiUrl(url);

  return (
    <article
      className={`rtc-card rtc-artifact${selected ? ' selected' : ''}`}
      data-artifact-id={artifact.id}
      onClick={() => onSelect?.(artifact.id)}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect?.(artifact.id);
        }
      }}
      role="button"
      tabIndex={0}
    >
      <header className="rtc-card-head">
        <span className="rtc-icon" aria-hidden="true">
          📄
        </span>
        <span className="rtc-title" title={artifact.path || artifact.name}>
          {artifact.name || artifact.path || artifact.id}
        </span>
        {size ? <span className="rtc-meta">{size}</span> : null}
      </header>
      <p className="rtc-status-line">
        {artifact.runId ? `Generated by ${artifact.runId}` : 'Artifact'}
        {artifact.mimeType ? ` · ${artifact.mimeType}` : ''}
      </p>
      <div className="rtc-actions">
        {safe ? (
          <a
            className="rtc-link-btn"
            href={safe}
            download=""
            onClick={(e) => e.stopPropagation()}
          >
            Download
          </a>
        ) : (
          <span className="rtc-muted">No download URL</span>
        )}
      </div>
    </article>
  );
}
